#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

require_once __DIR__ . '/components/Environment.php';
\app\components\Environment::load(__DIR__ . '/.env');

$environment = getenv('APP_ENV') ?: 'dev';
$debugValue = getenv('APP_DEBUG');
$debug = $debugValue === false
    ? $environment !== 'prod'
    : filter_var($debugValue, FILTER_VALIDATE_BOOL);

defined('YII_DEBUG') or define('YII_DEBUG', $debug);
defined('YII_ENV') or define('YII_ENV', $environment);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
